name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      # As etapas de OIDC client e Get Id Token geralmente não são necessárias para
      # a configuração básica do Static Web Apps, pois o token de implantação
      # da SWA e o repo_token já cuidam da autenticação.
      # Removi-as para simplificar e evitar possíveis conflitos.
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_WAVE_05348D80F }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # Para mais informações sobre as configurações de fluxo de trabalho do Static Web App, visite: https://aka.ms/swaworkflowconfig
          app_location: "ViagemImpacta/frontend" # Caminho para a pasta raiz do seu código-fonte do front-end
          api_location: "" # Deixe em branco, seu back-end já foi implantado separadamente
          output_location: "dist" # Pasta onde o Vite gera os arquivos de build (confirmado pela sua imagem)
          # O github_id_token não é necessário aqui, pois o azure_static_web_apps_api_token
          # já é o suficiente para a autenticação com o Static Web App.
          ###### Fim das Configurações de Repositório/Build ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_WAVE_05348D80F }}
          action: "close"
